Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,7 +43,15 @@ jobs:
           zip -r "../floom_core_build.zip" "Floom.Core"
           cd ..
 
-     # Upload the build artifact to the remote server
+          # Validate the zip file to make sure it's not zero bytes
+          echo "Checking if the zip file is created and not empty..."
+          if [ ! -s floom_core_build.zip ]; then
+              echo "Error: The zip file is empty or not created."
+              exit 1
+          fi
+          echo "Zip file created successfully and contains data."
+
+      # Upload the build artifact to the remote server
       - name: Upload build artifact to EC2
         run: |
           REMOTE_HOST="${{ secrets.REMOTE_HOST }}"
@@ -82,6 +90,16 @@ jobs:
             echo 'Unzipping the new build...'
             sudo unzip -o ~/$BUILD_ARCHIVE -d $REMOTE_DIR
 
+            echo 'Ensuring Floom.Core exists and cleaning up any conflicts...'
+            if [ -f $REMOTE_DIR/Floom.Core ]; then
+              echo 'A file named Floom.Core exists, removing it...'
+              sudo rm -f $REMOTE_DIR/Floom.Core
+            fi
+            if [ -d $REMOTE_DIR/Floom.Core ]; then
+              echo 'A directory named Floom.Core exists, removing it...'
+              sudo rm -rf $REMOTE_DIR/Floom.Core
+            fi
+
             echo 'Moving files from Floom.Core to the target directory...'
             sudo mv $REMOTE_DIR/Floom.Core/* $REMOTE_DIR
 
@@ -96,7 +114,6 @@ jobs:
 
             echo 'Deployment completed successfully.'
           "
-
 
       # Clean up local zip file
       - name: Clean up local zip file
